import React from 'react'
import styles from './styles.module.css'
export { QuizAnswer } from './QuizAnswer/QuizAnswer'
export { QuizForm } from './QuizForm/QuizForm'
import 'bootstrap/dist/css/bootstrap.min.css'
